export const blogPosts = [
  { slug: "structure-mvp-speed-stability", category: "Engineering", title: "How to Structure an MVP for Speed and Stability", excerpt: "Building fast doesn't mean building fragile. Here's a framework for shipping MVPs that can scale without starting over.", readTime: "6 min read" },
  { slug: "web-apps-fail-at-scale", category: "Architecture", title: "Why Most Web Applications Fail at Scale", excerpt: "Scalability isn't an afterthought — it's an architectural decision. We explore common patterns that break under pressure.", readTime: "8 min read" },
  { slug: "ux-strategy-product-success", category: "Design", title: "The Role of UX Strategy in Product Success", excerpt: "Great UX isn't just about pretty screens. It's about solving real problems through research-driven design decisions.", readTime: "5 min read" },
  { slug: "designing-systems-that-grow", category: "Design Systems", title: "Designing Systems That Grow With Your Business", excerpt: "Design systems aren't just for large teams. Learn how structured design accelerates development at any scale.", readTime: "7 min read" },
  { slug: "web-vs-mobile-first", category: "Strategy", title: "Web vs Mobile First — Making the Right Decision", excerpt: "The platform debate isn't one-size-fits-all. Here's how to make the right call based on your users and goals.", readTime: "6 min read" },
  { slug: "building-for-longevity", category: "Architecture", title: "Building for Longevity: Architecture Matters", excerpt: "Technical debt is the silent killer of products. We examine how clean architecture pays dividends over time.", readTime: "7 min read" },
  { slug: "startup-product-mistakes", category: "Startups", title: "Common Mistakes in Startup Product Development", excerpt: "From feature creep to premature optimization, here are the traps founders fall into — and how to avoid them.", readTime: "8 min read" },
  { slug: "design-systems-save-time", category: "Engineering", title: "Why Design Systems Save Engineering Time", excerpt: "A well-built design system is an investment that reduces development time, improves consistency, and enables faster iteration.", readTime: "5 min read" },
];
